index:
    path: /
    methods: GET
    controller: App\Controller\ProductController::index

uploads:
    path: /uploads/{filename}
    methods: GET
    controller: App\Controller\FileController::uploads

# Users
login:
    path: /login
    methods: GET
    controller: App\Controller\LoginController::login

auth_user:
    path: /login
    methods: POST
    controller: App\Controller\LoginController::authUser

logout:
    path: /logout
    methods: GET
    controller: App\Controller\LoginController::logout

register:
    path: /signup
    controller: App\Controller\UserController::register

show_user:
    path: /profile/{id}
    methods: GET
    controller: App\Controller\UserController::showUser

modify_user:
    path: /profile/{id}
    methods: POST
    controller: App\Controller\UserController::updateUser

list_users:
    path: /user/list
    methods: GET
    controller: App\Controller\UserController::listUsers

cart:
    path: /cart
    methods: GET
    controller: App\Controller\CartController::showCart

add_to_cart:
    path: /cart/add/{id}
    controller: App\Controller\CartController::addProduct

# Api
api_register:
    path: /api/register
    methods: POST
    controller: App\Controller\ApiUserController::register

api_login:
    path: /api/login
    methods: POST
    controller: App\Controller\ApiUserController::login

api_get_user:
    path: /api/user/{id}
    controller: App\Controller\ApiUserController::get

# Products
new_product:
    path: /product/new
    methods: GET
    controller: App\Controller\ProductController::newProduct

add_product:
    path: /product/new
    methods: POST
    controller: App\Controller\ProductController::addProduct

show_product:
    path: /product/{id}
    methods: GET
    controller: App\Controller\ProductController::showProduct

get_product:
    path: /api/product/{id}
    methods: GET
    controller: App\Controller\ProductController::getProductJson
